In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
%matplotlib inline

cap = cv2.VideoCapture(0)

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# Windows --> DIVX
# Linux or MacOs --> XVID

writer = cv2.VideoWriter("mysupervideo.mp4",cv2.VideoWriter_fourcc(*"XVID"),30,(width,height))

while True:
    
    ret,frame = cap.read()
    
    writer.write(frame)
    
    #gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    #cv2.imshow(winname = "Frame",mat = gray)
    
    cv2.imshow(winname = "Frame", mat = frame)
    
    if cv2.waitKey(1) & 0xFF == ord("q"):
        
        break
        
cap.release()
writer.release()
cv2.destroyAllWindows()

In [1]:
import cv2
import time
import numpy as np


cap = cv2.VideoCapture("mysupervideo.mp4")

if cap.isOpened() == False:
    print("Error File Not Found Or Wrong Codec Used!")
    

while cap.isOpened():
    
    ret,frame = cap.read()
    #print(ret,frame)
    
    if ret == True:
        
        
        # Writer 30 FPS
        # Burda önemi normalden hızlı video bunu 1/frame ile olması gereken hıza alıyoruz
        time.sleep(1/30)
        
        cv2.imshow("Frame",frame)
        
        if cv2.waitKey(10) & 0xFF == ord("q"):
            break
            
    else:
        
        break
            
cap.release()
cv2.destroyAllWindows()

True [[[62 59 53]
  [78 75 69]
  [83 80 74]
  ...
  [ 0  3  3]
  [ 0  3  3]
  [ 0  3  3]]

 [[65 62 56]
  [78 75 69]
  [78 75 69]
  ...
  [ 0  3  3]
  [ 0  3  3]
  [ 0  3  3]]

 [[70 67 61]
  [79 76 70]
  [72 69 63]
  ...
  [ 0  3  3]
  [ 0  3  3]
  [ 0  3  3]]

 ...

 [[ 0  1  0]
  [ 0  1  0]
  [ 0  1  0]
  ...
  [ 8 11  9]
  [ 8 11  9]
  [ 8 11  9]]

 [[ 0  1  0]
  [ 0  1  0]
  [ 0  1  0]
  ...
  [ 8 11  9]
  [ 8 11  9]
  [ 8 11  9]]

 [[ 0  1  0]
  [ 0  1  0]
  [ 0  1  0]
  ...
  [ 8 11  9]
  [ 8 11  9]
  [ 8 11  9]]]
True [[[248 251 249]
  [248 251 249]
  [248 251 249]
  ...
  [ 80  83 106]
  [ 82  84 105]
  [ 82  84 105]]

 [[248 251 249]
  [248 251 249]
  [248 251 249]
  ...
  [ 79  82 105]
  [ 81  83 104]
  [ 82  84 105]]

 [[248 251 249]
  [248 251 249]
  [248 251 249]
  ...
  [ 78  81 104]
  [ 80  82 103]
  [ 81  83 104]]

 ...

 [[ 48  57  58]
  [ 44  53  54]
  [ 50  59  60]
  ...
  [202 189 180]
  [202 189 180]
  [202 189 180]]

 [[ 45  54  55]
  [ 49  58  59]
  [ 46  55  56

True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 85  88 111]
  [ 84  85 108]
  [ 91  92 115]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 78  81 104]
  [ 81  82 105]
  [ 92  93 116]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 78  80 108]
  [ 78  81 106]
  [ 82  85 110]]

 ...

 [[ 92 100 104]
  [ 91  99 103]
  [ 88  96 100]
  ...
  [200 187 178]
  [200 187 178]
  [200 187 178]]

 [[ 88  96 100]
  [ 94 102 106]
  [ 96 104 108]
  ...
  [200 187 178]
  [200 187 178]
  [200 187 178]]

 [[ 93 101 105]
  [ 88  96 100]
  [ 88  96 100]
  ...
  [200 187 178]
  [200 187 178]
  [200 187 178]]]
True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 87  93 117]
  [ 87  90 115]
  [ 92  95 120]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 78  84 108]
  [ 84  87 112]
  [ 94  97 122]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 76  80 109]
  [ 80  85 112]
  [ 84  89 116]]

 ...

 [[ 92 100 104]
  [ 95 103 107]
  [ 93 101

True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 86  89 114]
  [ 91  92 115]
  [ 96  97 120]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 80  83 108]
  [ 86  87 110]
  [ 91  92 115]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 77  80 105]
  [ 83  86 109]
  [ 86  89 112]]

 ...

 [[ 99 108 114]
  [ 92 101 107]
  [ 96 105 111]
  ...
  [202 189 178]
  [202 189 178]
  [202 189 178]]

 [[ 93 102 108]
  [101 110 116]
  [111 120 126]
  ...
  [202 189 178]
  [202 189 178]
  [202 189 178]]

 [[101 110 116]
  [ 90  99 105]
  [ 97 106 112]
  ...
  [202 189 178]
  [202 189 178]
  [202 189 178]]]
True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 89  89 122]
  [ 91  90 120]
  [ 93  92 122]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 79  79 112]
  [ 85  84 114]
  [ 91  90 120]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 76  76 109]
  [ 82  83 113]
  [ 86  87 117]]

 ...

 [[ 96 105 111]
  [ 91 100 106]
  [ 98 107

True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 85  86 116]
  [ 87  86 116]
  [ 86  85 115]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 82  83 113]
  [ 85  84 114]
  [ 88  87 117]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 76  77 107]
  [ 84  83 113]
  [ 93  92 122]]

 ...

 [[ 95 102 108]
  [ 95 102 108]
  [ 99 106 112]
  ...
  [204 191 182]
  [204 191 182]
  [204 191 182]]

 [[100 107 113]
  [ 98 105 111]
  [ 98 105 111]
  ...
  [203 190 181]
  [203 190 181]
  [203 190 181]]

 [[ 96 103 109]
  [ 94 101 107]
  [ 94 101 107]
  ...
  [203 190 181]
  [203 190 181]
  [203 190 181]]]
True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 85  86 116]
  [ 87  86 116]
  [ 86  85 115]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 82  83 113]
  [ 85  84 114]
  [ 88  87 117]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 76  77 107]
  [ 84  83 113]
  [ 93  92 122]]

 ...

 [[ 88  95 101]
  [101 108 114]
  [107 114

True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 83  86 118]
  [ 86  87 117]
  [ 93  94 124]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 81  84 116]
  [ 86  87 117]
  [ 91  92 122]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 77  80 112]
  [ 84  85 115]
  [ 87  88 118]]

 ...

 [[104 113 119]
  [106 115 121]
  [106 115 121]
  ...
  [207 194 185]
  [207 194 185]
  [207 194 185]]

 [[105 114 120]
  [105 114 120]
  [105 114 120]
  ...
  [207 194 185]
  [207 194 185]
  [207 194 185]]

 [[110 119 125]
  [106 115 121]
  [101 110 116]
  ...
  [207 194 185]
  [207 194 185]
  [207 194 185]]]
True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 82  86 115]
  [ 87  90 115]
  [ 96  99 124]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 80  84 113]
  [ 86  89 114]
  [ 92  95 120]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 75  79 108]
  [ 83  86 111]
  [ 87  90 115]]

 ...

 [[104 113 119]
  [104 113 119]
  [107 116

True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 87  89 117]
  [ 92  93 118]
  [ 93  94 119]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 84  86 114]
  [ 86  87 112]
  [ 86  87 112]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 82  84 112]
  [ 86  89 114]
  [ 89  92 117]]

 ...

 [[104 113 119]
  [108 117 123]
  [117 126 132]
  ...
  [208 195 186]
  [208 195 186]
  [208 195 186]]

 [[104 113 119]
  [105 114 120]
  [107 116 122]
  ...
  [208 195 186]
  [208 195 186]
  [208 195 186]]

 [[125 134 140]
  [114 123 129]
  [103 112 118]
  ...
  [208 195 186]
  [208 195 186]
  [208 195 186]]]
True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 89  91 119]
  [ 93  94 119]
  [ 94  95 120]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 85  87 115]
  [ 87  88 113]
  [ 87  88 113]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 83  85 113]
  [ 87  90 115]
  [ 90  93 118]]

 ...

 [[105 114 120]
  [110 119 125]
  [117 126

True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 87  93 122]
  [ 89  94 121]
  [ 90  95 122]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 85  91 120]
  [ 85  90 117]
  [ 90  95 122]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 75  81 110]
  [ 84  89 116]
  [ 96 101 128]]

 ...

 [[113 125 130]
  [115 127 132]
  [113 125 130]
  ...
  [209 196 187]
  [209 196 187]
  [209 196 187]]

 [[123 135 140]
  [112 124 129]
  [110 122 127]
  ...
  [209 196 187]
  [209 196 187]
  [209 196 187]]

 [[102 114 119]
  [111 123 128]
  [110 122 127]
  ...
  [209 196 187]
  [209 196 187]
  [209 196 187]]]
True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 89  95 124]
  [ 89  94 121]
  [ 94  99 126]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 86  92 121]
  [ 87  92 119]
  [ 92  97 124]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 75  81 110]
  [ 90  95 122]
  [ 95 100 127]]

 ...

 [[112 124 129]
  [113 125 130]
  [115 127

True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 87  88 118]
  [ 92  91 121]
  [ 96  95 125]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 83  84 114]
  [ 88  87 117]
  [ 93  92 122]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 80  80 113]
  [ 86  86 119]
  [ 92  92 125]]

 ...

 [[108 118 122]
  [124 134 138]
  [119 129 133]
  ...
  [209 196 187]
  [209 196 187]
  [209 196 187]]

 [[114 124 128]
  [112 122 126]
  [117 127 131]
  ...
  [209 196 187]
  [209 196 187]
  [209 196 187]]

 [[119 129 133]
  [113 123 127]
  [114 124 128]
  ...
  [209 196 187]
  [209 196 187]
  [209 196 187]]]
True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 87  88 118]
  [ 92  91 121]
  [ 96  95 125]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 83  84 114]
  [ 88  87 117]
  [ 93  92 122]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 80  80 113]
  [ 86  86 119]
  [ 92  92 125]]

 ...

 [[106 116 120]
  [124 134 138]
  [118 128

True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 83  89 118]
  [ 82  87 114]
  [ 87  92 119]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 79  85 114]
  [ 82  87 114]
  [ 85  90 117]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 78  82 111]
  [ 82  87 114]
  [ 85  90 117]]

 ...

 [[102 109 115]
  [103 110 116]
  [106 113 119]
  ...
  [208 195 186]
  [208 195 186]
  [208 195 186]]

 [[107 114 120]
  [110 117 123]
  [107 114 120]
  ...
  [208 195 186]
  [208 195 186]
  [208 195 186]]

 [[102 109 115]
  [106 113 119]
  [ 94 101 107]
  ...
  [208 195 186]
  [208 195 186]
  [208 195 186]]]
True [[[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 83  89 118]
  [ 82  87 114]
  [ 87  92 119]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 79  85 114]
  [ 82  87 114]
  [ 85  90 117]]

 [[250 253 251]
  [250 253 251]
  [250 253 251]
  ...
  [ 78  82 111]
  [ 82  87 114]
  [ 85  90 117]]

 ...

 [[105 112 118]
  [109 116 122]
  [109 116

In [6]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

x = width // 2
y = height // 2

w = width // 4
h = height // 4
 
while True:
    
    ret, frame = cap.read()
    #print(width,height)
    
    cv2.rectangle(frame,(x,y),(x+w, y+h),(0,0,255),thickness = 4)
    
    cv2.imshow("Frame",frame)
    
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break
        
cap.release()
cv2.destroyAllWindows()

1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1280 720
1

In [22]:
import cv2

# Linux or MacOs --- > XVID
# writer = cv2.VideoWriter("myvideo.mp4",cv2.VideoWriter_fourcc(*"XVID",30,(width,height)))

## CALLBACK FUNCTION RECTANGLE

def draw_rectangle(event,x,y,flags,param):
    
    global pt1,pt2,topLeft_Clicked,botRight_Clicked
    
    if event == cv2.EVENT_LBUTTONDOWN:
        
        if topLeft_Clicked == True and botRight_Clicked == True:
            
            pt1 = (0,0)
            pt2 = (0,0)
            topLeft_Clicked = False
            botRight_Clicked = False
        
        # Burda şunu düşünme zaten ikiside False Hemen ikiside aynı değer alıcak gibi düşünme
        # Sırası ile gider yani ilk tıkladığında topLeft girer ikinci tıkladığında ise botRight girer devreye
        
        if topLeft_Clicked == False:
            
            pt1 = (x,y)
            topLeft_Clicked = True
            
        elif botRight_Clicked == False:
        
            pt2 = (x,y)
            botRight_Clicked = True
            
## GLOBAL VARIABLES

pt1 = (0,0)
pt2 = (0,0)
topLeft_Clicked = False
botRight_Clicked = False

## CONNECT TO THE CALLBACK

cap = cv2.VideoCapture(0)

cv2.namedWindow("Test")
cv2.setMouseCallback("Test",draw_rectangle)


while True:
    
    ret,frame = cap.read()
    
    #writer.write(frame)
    
    if topLeft_Clicked:
        
        cv2.circle(frame,pt1,5,(0,0,255),thickness = -1)
    
    #print(pt1,pt2)
    
    if topLeft_Clicked and botRight_Clicked:
        
        cv2.rectangle(frame,pt1,pt2,(0,0,255),3)
        
        
    cv2.imshow("Test",frame)
        
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break
        
        
cap.release()
cv2.destroyAllWindows()

In [2]:
deneme = "ali"

def test():
    
    global deneme
    
    deneme = "gökhan"
    print(deneme)

test()
print(deneme)

gökhan
gökhan


In [17]:
deneme1 = False
deneme2 = False

if deneme1 == False:

        print("Deneme1")
        deneme1 = True

elif deneme2 == False:

        print("Deneme2")
        deneme2 = True

Deneme1


In [18]:
deneme1,deneme2

(True, False)

In [19]:
if deneme1 == False:

        print("Deneme1")
        deneme1 = True

elif deneme2 == False:

        print("Deneme2")
        deneme2 = True

Deneme2


In [20]:
deneme1,deneme2

(True, True)

In [21]:
if deneme1 == False:

        print("Deneme1")
        deneme1 = True

elif deneme2 == False:

        print("Deneme2")
        deneme2 = True